---
name: Tests
run-name: "Tests (${{ github.head_ref || github.ref_name }})"

on:
  pull_request:
    branches:
      - main

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup CICD
        uses: ./.github/actions/cicd_setup

      - name: Actionlint
        run: |
          source .venv/bin/activate
          invoke debug.env
          invoke tests.actionlint

  check_agents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup CICD
        uses: ./.github/actions/cicd_setup

      - name: Check Agents
        run: |
          source .venv/bin/activate
          invoke debug.env
          invoke tests.check_agents

  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup CICD
        uses: ./.github/actions/cicd_setup

      - name: Pylint
        run: |
          source .venv/bin/activate
          invoke debug.env
          invoke tests.pylint

  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup CICD
        uses: ./.github/actions/cicd_setup

      - name: Pytest
        run: |
          source .venv/bin/activate
          invoke debug.env
          invoke tests.pytest

  ruff_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup CICD
        uses: ./.github/actions/cicd_setup

      - name: Ruff Lint
        run: |
          source .venv/bin/activate
          invoke debug.env
          invoke tests.rufflint

  yaml_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup CICD
        uses: ./.github/actions/cicd_setup

      - name: YAML Lint
        run: |
          source .venv/bin/activate
          invoke debug.env
          invoke tests.yamllint
